const projects = [
    {
      key: 'capital-conseil-immobilier',
      name: 'Capital Conseil Immobilier',
      img: 'conseil-immo-cover.jpg',
      excerpt: 'A website for a rental house agency near Toulouse.',
      titlepage:'Capital Conseil Immobilier charge me to rethink their website',
      imgHeader:'header-conseil-immo.jpg',
      titleBody:'a solution to help them',
      titleSpan:'We\'ve built together',
      imgBody:'capital-immo-responsive.jpg',
      textBody:'Capital Conseil Immobilier is a house rental agency near Toulouse at Bouloc. They needed a website to shared there rentals and sales online.',
      titleBody2:'around filter search',
      titleSpan2:'Website think',
      imgBody2 :'capital-immo-2.gif',
      textBody2:'We choosed to built website, around 3 main features : Rentals, Solds and estimate customers project.',
      titleBody3:'new sales and rentals',
      titleSpan3:'Easy to create',
      imgBody3 :'capital-immo-3.png',
      textBody3:'Because plugins are made for handle of any situation, they make websites slower. That why, we take decision to create a custom plugins dedicate to they only uses',
      strategy: 'Audit\nProject Design\nSeo',
      design: 'Design UI/UX\nResponsive design',
      development:'CMS Worpdress\nPlugins',
    },
      {
        key: 'apair-prod',
        name: 'Apair Prod',
        img: 'apair-prod-cover.jpg',
        excerpt: 'A website for a recording studio near Toulouse',
        titlepage:'Website and digital strategy of communication for Apair Prod',
        imgHeader:'header-apairprod.jpg',
        titleBody:'a solution to help them',
        titleSpan:'We\'ve built together',
        imgBody:'apairprod-responsive.jpg',
        textBody:'ApairProd is a studio recording. After   meeting with them, We decide to design there website aroud 3 sections :\n- How are we\n- What we doing\n- Automatic financial estimate',
        titleBody2:'to the result',
        titleSpan2:'Take a look',
        imgBody2 :'apairprod-2.gif',
        titleBody4:'communication',
        titleSpan4:'Instagram',
        textBody4:'We choosed to built website, around 3 main features : Rentals, Solds and estimate customers project.',
        imgBody4 :'apairprod-4.jpg',
        strategy: 'Audit\nProject Design\nSeo',
        design: 'Design UI/UX\nResponsive design',
        development:'CMS Worpdress\nForm for project\'s estiamte',
      },
      {
        key: 'comenpoche',
        name: 'Com en poche',
        img: 'comenpoche-cover.jpg',
        excerpt: 'A website for my freelance activity',
        titlepage:'Personal website for selling digital services',
        imgHeader:'header-comenpoche.jpg',
        titleBody:'of services',
        titleSpan:'A quick presentation',
        imgBody:'comenpoche-responsive.jpg',
        textBody:'I choose to create a design witch some effect of parallax, built in Js with TweenMax. Through it design, I wanted a wow effect. To catch users attention, I showing my habilities to handle UX design.',
        titleBody2:'of digital communication',
        titleSpan2:'Complete services',
        textBody2:'I propose to creat Branding, Website and digital Ads.',
        imgBody2 :'comenpoche.gif',
        strategy: 'Audit\nProject Design\nSeo',
        design: 'Design UI/UX\nResponsive design',
        development:'From scratch\nTweenMax librairy',
      },
      {
        key: 'quiet-good-ux-application',
        name: 'QGUX Mobile app',
        img: 'app-fruit-cover.jpg',
        excerpt: 'An application to help people find season fruits and vegetable.',
        titlepage:'Personal projets for knowing fruits and vegetable of season',
        imgHeader:'header-qgux.jpg',
        titleBody:'ongoing project',
        titleSpan:'Just a Preview',
        imgBody:'qgux.gif',
        textBody:'A simple application create with React Native, for helping people to knowing witch fruits and vegetables are of season or not. For a responsible purchasing.',
        strategy: 'Audit\nProject Design',
        design: 'Design UI/UX',
        development:'React Native',
      },
  
]

  
  export default projects

